### ISSUE TITLE
New reset connection codes

### ISSUE THREAD

**Issue by Gyropyro** [forairan/Agar.io-Protocol#4]
The reset connection codes have changed:

Unmasked payloads:

fe 05 00 00 00
ff 23 12 38 09

These should be updated at the bottom of the document! :)

**Comment by Gyropyro** [comment]
To save others the effort, these correspond with:
5 (reset connection 1)
588396553 (reset connection 2)

**Comment by Ephemerality** [comment]
Didn't know anyone still read this. Not sure where you got the value for 255 from, it's still 154669603 in the agar.io client I'm seeing.  
Updated 254.

**Comment by Gyropyro** [comment]
Thanks for responding.

I double checked, and still giving the value '588396553' for me (running wireshark).
This is straight off agar.io, no private servers or mods.
Perhaps this could some other significance between users/servers?

:+1:

**Comment by vram4** [comment]
@Gyropyro Byte order is in little endian, so the bytes are read in reverse. Ex. "0A 24 1F 50" would read as "50 1F 24 0A"

**Comment by Gjum** [comment]
588396553 is another (byte-inverted) interpretation of 154669603. One of you uses Little, the other one Big Endian. 154669603 is right.

@vram4 dammit! 10sec too late!

**Comment by Gyropyro** [comment]
My mistake, should have read the docs better! Cheers!
