### ISSUE TITLE
Client Bound 18 not documented

### ISSUE THREAD

**Issue by Gegy** [forairan/Agar.io-Protocol#6]
I've been working on an agar.io client recently and have found this very useful, but I have begun to receive packet id 18 from the server, not sure what it is, it doesn't contain any data except for it's id.

**Comment by Gjum** [comment]
Packet 18 is indeed a new one, like 20 it resets the known and controlled cells.

I'm not sure if this repo is still being updated, but this wiki is: http://agar.gcommer.com/index.php?title=Protocol

**Comment by Gegy** [comment]
Ah, okay, I just checked that a few hours ago and the packet wasn't there - so it must have been very recently updated! Thanks! :)
